###############################################################################
# NAME:		    ProjectSerializerTest.mk
#
# AUTHOR:	    Ethan D. Twardy <edtwardy@mtu.edu>
#
# DESCRIPTION:	    Makefile for the ProjectSerializer module test.
#
# CREATED:	    08/12/2018
#
# LAST EDITED:	    08/19/2018
###

# TODO: Remove these flags

MODULE:=ProjectSerializer
CFLAGS += -I test/ -DTEST_MODULE=Project \
-Wno-unused-parameter \
-Wno-unused-function

obj-$(MODULE):=test/$(MODULE)Test/$(MODULE)Test.c \
test/SerializerTest.c \
source/RuntimeLibrary/Serializer/$(MODULE).c

#: Run the test, then clean.
all: $(MODULE)Test $(MODULE)clean

#: Run the test.
$(MODULE)Test: test/$(MODULE)Test/$(MODULE)Test
	dir=`pwd`; cd test/$(MODULE)Test/; $(MODULE)Test; cd $$dir

#: Generate the test executable.
test/$(MODULE)Test/$(MODULE)Test: force
	$(CC) $(CFLAGS) $(obj-$(MODULE)) $(LDFLAGS) -o $@

force:

#: Remove any files generated by this Makefile
$(MODULE)clean:
	rm -f test/$(MODULE)Test/$(MODULE)Test
	rm -f $(obj-$(MODULE))

##############################################################################
