###############################################################################
# NAME:		    ScrumExceptTest.mk
#
# AUTHOR:	    Ethan D. Twardy <edtwardy@mtu.edu>
#
# DESCRIPTION:	    Makefile for the ScrumExcept module test.
#
# CREATED:	    08/12/2018
#
# LAST EDITED:	    08/12/2018
###

MODULE:=ScrumExcept
CFLAGS += -I test/

obj-$(MODULE):=test/$(MODULE)Test/$(MODULE)Test.o \
test/TestHarness.o \
source/RuntimeLibrary/$(MODULE).o

#: Run the test, then clean.
all: $(MODULE)Test $(MODULE)clean

#: Run the test.
$(MODULE)Test: test/$(MODULE)Test/$(MODULE)Test
	-./test/$(MODULE)Test/$(MODULE)Test

#: Generate the test executable.
test/$(MODULE)Test/$(MODULE)Test: $(obj-$(MODULE))

#: Generate dependencies
$(obj-$(MODULE)): force

force:

#: Remove any files generated by this Makefile
$(MODULE)clean:
	rm -f test/$(MODULE)Test/$(MODULE)Test
	rm -f $(obj-$(MODULE))

##############################################################################
