###############################################################################
# NAME:		    Makefile
#
# AUTHOR:	    Ethan D. Twardy <edtwardy@mtu.edu>
#
# DESCRIPTION:	    This Makefile sets the obj-lib variable, which contains
#		    targets to build for the RuntimeLibrary.
#
# CREATED:	    08/21/2018
#
# LAST EDITED:	    08/21/2018
###

obj-lib += Serializer/ProjectSerializer.o
obj-lib += Serializer/SerializerConfig.o
obj-lib += ScrumExcept.o

##############################################################################
