###############################################################################
# NAME:		    Makefile
#
# AUTHOR:	    Ethan D. Twardy
#
# DESCRIPTION:	    Target Makefile for the development client.
#
# CREATED:	    07/01/2018
#
# LAST EDITED:	    07/01/2018
###

obj-c+=client.o
obj-c+=autoscrumServer.o
obj-c+=devClientConfig.o

###############################################################################
