###############################################################################
# NAME:		    Makefile
#
# AUTHOR:	    Ethan D. Twardy
#
# DESCRIPTION:	    Target Makefile for the autoscrum server.
#
# CREATED:	    07/01/2018
#
# LAST EDITED:	    07/05/2018
###

obj-s+=serve/autoscrum.o
obj-s+=serve/autoscrumClient.o

###############################################################################
